load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "fst",
    srcs = [
        "bridge.c",
        "bridge.h",
        "callbacks.go",
        "fst.go",
        "hier.go",
    ],
    # keep
    cdeps = ["//third_party/libfst"],
    cgo = True,
    importpath = "github.com/filmil/go-vcd-parser/fst",
    visibility = ["//visibility:public"],
    deps = ["//vcd"],
)
