load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "cvt",
    srcs = [
        "pkg.go",
        "sink.go",
    ],
    importpath = "github.com/filmil/go-vcd-parser/cvt",
    visibility = ["//visibility:public"],
    deps = [
        "//db",
        "//fst",
        "//vcd",
        "@com_github_davecgh_go_spew//spew",
        "@com_github_golang_glog//:glog",
    ],
)

go_test(
    name = "cvt_test",
    size = "small",
    srcs = [
        "fst_test.go",
        "pkg_test.go",
    ],
    data = glob(["testdata/**"]),
    deps = [
        ":cvt",
        "//db",
        "//dbt",
        "//vcd",
    ],
)
